### ISSUE TITLE
Please make the installation instructions

### ISSUE THREAD

**Issue by testinghere57564** [edgd1er/nordvpn-proxy#11]
It would be really cool if you did a guide on how to install this for Windows / Linux Docker compose. Personally, I'm not familiar with docker at all, it's unrealistic to find a video demonstrating how to deploy such a solution to YouTube.
P.S. Still can't get it to install.

**Comment by edgd1er** [comment]
I thought the README was clear. What information would you like to see to know how to start the container:
here is something that may help you.
* Just copy/paste the grey text block starting with version 3.8. to a file named docker-compose.yml
* Set values for NORDVPN_TECHNOLOGY, NORDVPN_PROTOCOL, NORDVPN_COUNTRY
* adapt if needed LOCAL_NETWORK, TZ
* create file nordvpn_login containing your login, nordvpn_pass containing your  password
* start the container: docker compose up -d

once the container is started, you will see in the logs these two lines:
```
nordvpn-proxy-proxy-1  | INFO: OPENVPN: up: starting tinyproxy
.....
nordvpn-proxy-proxy-1  | ok: run: tinyproxy: (pid 103) 1s, normally down
```

**Comment by edgd1er** [comment]
I'll close that issue.
Please let me know if you need more information.
