### ISSUE TITLE
./run: line 61: NORDVPN_LOGIN: unbound variable

### ISSUE THREAD

**Issue by jsoyer** [edgd1er/nordvpn-proxy#12]
Hello,

Thanks for the great work! unfortunately even if i follow the instruction that are on the docker hub portal, i still have an issue when i run the container:

./run: line 61: NORDVPN_LOGIN: unbound variable

I have tried to debug and found that the variable is used inside the run script instead of NORDVPN_USER.

This is the command line that I refer to:

docker run -it --rm --cap-add NET_ADMIN -p 1080:1080 -e NORDVPN_USER=<email> -e NORDVPN_PASS='<pass>' -e NORDVPN_COUNTRY=Poland
 -e NORDVPN_PROTOCOL=udp -e NORDVPN_CATEGORY=p2p   edgd1er/nordvpn-proxy

Suggestions:

* Setting the NORDVPN_LOGIN at the creation of the container instead of NORDVPN_USER and changing the documentation on the Docker hub repository
* Replacing all the occurence of NORDVPN_LOGIN with NORDVPN_USER

Maybe some other solutions exist but those are the most straight forward :-)

Thanks

Best Regards,
Jerome

**Comment by edgd1er** [comment]
thank you for your report and the comments.
I'm sorry I didn't not update docker's hub README with latest information.
I added information and a docker-compose.yml sample with explanation.

Please let me know if more information is needed.

there is also a new var NORDVPN_SERVER, allowing to select directly a server, bypassing nordvpn's api. 
I hope the github's README has all information needed.

PS: the image was updated today.( 2022/01/15)
