### ISSUE TITLE
Option to silence cron script execution

### ISSUE THREAD

**Issue by alpe12** [edgd1er/nordvpn-proxy#13]
The log gets a lot of:
```
crond: USER root pid 63198 cmd /etc/service/openvpn/healthcheck.sh
crond: USER root pid 63199 cmd /etc/service/openvpn/resolvcheck.sh
```

If possible, add an option to silence it.

[Cron loglevel 9 should work](https://forum.openwrt.org/t/how-do-i-completely-silence-a-cron/30116/3).
Thanks.

**Comment by edgd1er** [comment]
Yes, one every minute, + another script every 5 minutes , and a third one every 15 minutes.
Thanks for pointing out to a solution, I'll have a look at it.

**Comment by edgd1er** [comment]
Hi @alpe12 ,
please test.
According to my rapid tests, crond is running and there is no more cron logs. added info into README and docker-compose.yml sample.

**Comment by alpe12** [comment]
Appears to be working, thanks. :)
