### ISSUE TITLE
NORDVPN_CREDS?

### ISSUE THREAD

**Issue by DennisGaida** [edgd1er/nordvpn-proxy#18]
Usually docker secrets contain one information (i.e. username or password), not multiple.

With your latest commit https://github.com/edgd1er/nordvpn-proxy/commit/f99564da8aa8c4939ac3854de7b3ff014282a6bc you just introduced a breaking change removing `NORDVPN_LOGIN` and `NORDVPN_PASS` replacing it with `NORDVPN_CREDS`. Unfortunately I can't roll back a version using docker hub as a registry since there aren't any tags.

I can't find any example for the `NORDVPN_CREDS` secrets file. Should it just be login & password newline delimited?

**EDIT:** just checked the commit and you are doing 
```
   NORDVPN_LOGIN=$(cat /run/secrets/NORDVPN_CREDS| head -1)
    NORDVPN_PASS=$(cat /run/secrets/NORDVPN_CREDS| tail -1)
```
I mean, I can create a NORDVPN_CREDS file just like that, but I actually was happy with LOGIN & PASS. Why the change? Why this crude method of doing  `head` and `tail` on the file? I liked it better before 😉

**Comment by edgd1er** [comment]
Thanks for your interest in the project.
I agree, that change was not so much documented. it is now :) As for the change, i wanted something simplier to handle login and password and mostly to a, but I understand you may have a preference for two files handling the nordvpn secret. is 

Your are right NORDVPN_CREDS is two lines file, login one the first, password on the second.

FYI, i'm putting my efforts into add wireguard on another similar project (nordlynx_proxy), so this one may not evolve anymore, except for image or software updates

**Comment by DennisGaida** [comment]
Thanks for the heads-up. I have seen nordlynx_proxy as well but also the problems with the necessary NordVPN login being deprecated.

I might switch to gluetun and you should maybe check it out as well: https://github.com/qdm12/gluetun

**Comment by edgd1er** [comment]
thanks for the suggestion. I'll have a look to it, although I didn't see nordvpn features like killswitch, cybersec, ...
I didn't see neither, the nordvpn api's use to select a server, hence the configurations is manual.

A the moment, the login process doesn't throw a warning about not being available soon.

wireguard that looks promising but adds 317MB overload to the image.
