### ISSUE TITLE
OpenVPN deprecated cipher option warning

### ISSUE THREAD

**Issue by discosultan** [edgd1er/nordvpn-proxy#25]
Seeing the following in OpenVPN logs:

> DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning

**Comment by edgd1er** [comment]
Thanks for letting me know. The openvpn file is downloaded from the NORDVPN servers, this need to be corrected by Nordvpn.I guess a find and replace might fix this, temporarily. I'll have a look, whenever possible.

**Comment by discosultan** [comment]
Thanks for the response. Wasn't aware the config is downloaded. Not sure if it's worth "fixing" it here then. Sounds like an upstream issue. Feel free to close if you decide not to take action on it :)

**Comment by edgd1er** [comment]
commit 0d7a76b424aa9075a23494e998a4dc67a3c0d924 should fix the problem.

**Comment by discosultan** [comment]
Thank you @edgd1er ! Can confirm that the warning is no longer there.
